### ISSUE TITLE
Tab Completions don't work after restart of powershell

### ISSUE THREAD

**Issue by bobbytreed** [lzybkr/TabExpansionPlusPlus#33]
After initial install using "Install-Module" all tab completions work as expected. Upon restart of powershell, and import of TabExpansion++, most tab completions do not work.  Specific ones tested were the net use in the WindowsExe.ArgumentCompleters.

Probably doing something wrong, just not sure what.  Figured the solution was pretty simple so I didn't do much troubleshooting on my own due to my unfamiliarity with the code.

Running Powershell 5.0

**Comment by lzybkr** [comment]
How long did you wait before trying?  After loading the module, there is some work that's done in the background which may not have completed - and if that's the case, then you'd see the behavior you described.

**Comment by gfody** [comment]
I noticed this for [psgoogle](https://github.com/gfody/PsGoogle). If the module is imported automatically the first time you use it, it seems the first tab completion will always fail. As a workaround I'm just explicitly importing the module in my profile.

**Comment by lzybkr** [comment]
It pays to look at the year, I thought this issue was opened 3 days from the future :)

Regarding psgoogle, I think TabExpansion++ is getting loaded by the call to Register-ArgumentCompleter after the psgoogle module is loaded.  So if you want tab completion before the module is loaded, you do need to load it in your profile.

@bobbytreed - I think PSGet loads the module automatically after install, so you do need to load it explicitly in your module.
