### ISSUE TITLE
Auto-completers aren't registered for parameter aliases

### ISSUE THREAD

**Issue by pcgeek86** [lzybkr/TabExpansionPlusPlus#46]
I've noticed that the `TabExpansion++` PowerShell module's `Register-ArgumentCompleter` command only registers an argument completer, when a parameter's **name** is matched. If a parameter has an **alias** that matches the value specified for the `-ParameterName` parameter, the auto-completer is not registered.

My recommendation would be to ensure that `TabExpansion++` registers argument completers for commands with parameter aliases that match the value specified by the `-ParameterName` parameter on the `Register-ArgumentCompleter` command.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by lzybkr** [comment]
I don't plan on fixing this because it encourages a bad practice of registering a completer for an alias and the non-aliased parameter.

The PowerShell completion engine resolves parameter aliases to their real parameter names before attempting completion, so TabExpansionPlusPlus would have to resolve those aliases as well.  It's not a big burden on the completion author to ensure they don't use aliases - the helper Get-CommandWithParameter exported by this module helps with this as well by not returning commands where the parameter name is an alias.
